title: Ethan Shen
twitter_username: ethnlshn
email: ethans03@cs.washington.edu
github_username: ethanlshen
scholar: ES3rEEUAAAAJ&hl
url: "https://ethanlshen.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: "/"
 - name: "Resume"
   link: "resume.pdf"
