#!/usr/bin/env python3
"""Build _data/galleries.yml from photos/photography/<gallery>/ subfolders.

Layout:
    photos/photography/
        <gallery_id>/
            _meta.yml         # optional
            <photo>.jpg
            <photo>.min.jpg   # auto-generated if missing

_meta.yml fields (all optional):
    title:  display name          (default: folder name, title-cased)
    cover:  filename of cover     (default: first photo, filename-sorted)
    order:  sort index — higher values appear first (default: unordered — sorted after ordered)

For each photo, a sibling `<stem>.min<ext>` thumbnail (longest side
<= THUMB_MAX px) is generated if it does not already exist.

Run:
    source venv/bin/activate
    python scripts/build_galleries.py
"""
from pathlib import Path
import sys
import yaml
from PIL import Image

REPO = Path(__file__).resolve().parent.parent
PHOTOS_DIR = REPO / "photos" / "photography"
OUT = REPO / "_data" / "galleries.yml"

IMAGE_EXTS = {".jpg", ".jpeg", ".png"}
THUMB_MAX = 1200
THUMB_QUALITY = 80


def is_original_image(p: Path) -> bool:
    if not p.is_file() or p.suffix.lower() not in IMAGE_EXTS:
        return False
    # exclude thumbnails (stem like "foo.min")
    return not p.stem.lower().endswith(".min")


def list_photos(folder: Path):
    return sorted(
        (p for p in folder.iterdir() if is_original_image(p)),
        key=lambda p: p.name.lower(),
    )


def min_path_for(photo: Path) -> Path:
    return photo.with_name(photo.stem + ".min" + photo.suffix)


def ensure_min(photo: Path) -> Path:
    mp = min_path_for(photo)
    if mp.exists():
        return mp
    print(f"  + thumbnail: {mp.relative_to(REPO)}")
    with Image.open(photo) as im:
        im.thumbnail((THUMB_MAX, THUMB_MAX))
        im.convert("RGB").save(mp, "JPEG", quality=THUMB_QUALITY, optimize=True)
    return mp


def read_meta(folder: Path) -> dict:
    mf = folder / "_meta.yml"
    if mf.exists():
        with open(mf) as f:
            return yaml.safe_load(f) or {}
    return {}


def rel(p: Path) -> str:
    return "./" + p.relative_to(REPO).as_posix()


def image_size(p: Path):
    with Image.open(p) as im:
        return im.size


def build_gallery(folder: Path) -> dict | None:
    meta = read_meta(folder)
    photos = list_photos(folder)
    if not photos:
        print(f"skip {folder.name}: no images")
        return None

    print(f"processing {folder.name} ({len(photos)} photos)")

    # Cover
    cover_name = meta.get("cover")
    if cover_name:
        cover = folder / cover_name
        if not cover.exists():
            print(f"  warning: cover '{cover_name}' missing; using first photo")
            cover = photos[0]
    else:
        cover = photos[0]
    cover_min = ensure_min(cover)
    cw, ch = image_size(cover)

    title = meta.get("title") or folder.name.replace("-", " ").replace("_", " ").title()

    entry = {
        "id": folder.name,
        "title": title,
        "cover": rel(cover),
        "cover_min": rel(cover_min),
        "cover_width": cw,
        "cover_height": ch,
        "photos": [],
    }

    for p in photos:
        mp = ensure_min(p)
        w, h = image_size(p)
        entry["photos"].append({
            "path": rel(p),
            "min_path": rel(mp),
            "width": w,
            "height": h,
        })

    if "order" in meta:
        entry["_order"] = meta["order"]
    return entry


def build():
    if not PHOTOS_DIR.is_dir():
        sys.exit(f"missing {PHOTOS_DIR}")

    galleries = []
    for folder in sorted(PHOTOS_DIR.iterdir()):
        if not folder.is_dir():
            continue
        # skip dotfolders and Jekyll build artifacts
        if folder.name.startswith(".") or folder.name.startswith("_"):
            continue
        g = build_gallery(folder)
        if g is not None:
            galleries.append(g)

    # Sort: explicit `order` first (descending — higher values first), then the rest alphabetically by id
    galleries.sort(key=lambda g: (0, -g["_order"]) if "_order" in g else (1, g["id"]))
    for g in galleries:
        g.pop("_order", None)

    header = (
        "# Auto-generated by scripts/build_galleries.py. DO NOT EDIT BY HAND.\n"
        "# Edit photos/photography/<gallery>/_meta.yml (or drop photos in/out\n"
        "# of those folders) and re-run: python scripts/build_galleries.py\n"
    )
    with open(OUT, "w") as f:
        f.write(header)
        yaml.safe_dump(galleries, f, sort_keys=False, allow_unicode=True, width=4096)
    print(f"wrote {OUT.relative_to(REPO)} ({len(galleries)} galleries)")


if __name__ == "__main__":
    build()
